In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from keras.preprocessing import image
import os
import shutil 
import cv2
from imutils import paths
from keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model


In [2]:
os.path.exists("with_mask")

True

In [3]:

data = []
label = []

folder_path1 = "with_mask"
for i in os.listdir(folder_path1):
    if not i.startswith('.') and i.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".gif")):
        image_path = os.path.join(folder_path1, i)
        image = load_img(image_path, target_size=(224,224))
        image = img_to_array(image)
        data.append(image)
        label.append("with_mask")

folder_path2 = "without_mask"
for i in os.listdir(folder_path2):
    if not i.startswith('.') and i.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".gif")):
        image_path = os.path.join(folder_path2, i)
        image = load_img(image_path, target_size=(224,224))
        image = img_to_array(image)
        data.append(image)
        label.append("without_mask")

C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\PIL\Image.py:981: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [4]:
len(data)

3833

In [5]:
len(label)

3833

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
labels = le.fit_transform(label)

In [7]:
type(labels)
labels.shape
labels

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [8]:
x = np.array(data)
y = np.array(labels)

In [9]:
y[0]

0

In [10]:
x[1].shape

(224, 224, 3)

performing scaling on the dataset (normalization)

In [11]:
x = x / 255  # Normalize by dividing by max pixel value (255 for 8-bit images)

In [12]:
y
# x

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [13]:
x.shape

(3833, 224, 224, 3)

In [14]:
y.shape

(3833,)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [16]:
x_train.shape

(3066, 224, 224, 3)

In [17]:
y_train.shape

(3066,)

In [18]:
from keras.applications.vgg16 import VGG16

In [19]:
vgg = VGG16()

In [21]:
from keras import Sequential
model = Sequential()


In [23]:
for layer in model.layers:
    layer.trainable=False

In [24]:
from tensorflow.keras.layers import Dense
model.add(Dense(224,activation = "relu"))
model.add(Dense(112,activation = "relu"))
model.add(Dense(56,activation = "relu"))
model.add(Dense(1,activation='sigmoid'))

In [25]:
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics = ["accuracy"])
# //normalization / standardization / scaling
# checking accuracy!
# how eda is different from data processing
# batch size
# flattan

In [26]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
96/96 ━━━━━━━━━━━━━━━━━━━━ 1277s 13s/step - accuracy: 0.6326 - loss: 0.6219 - val_accuracy: 0.9048 - val_loss: 0.2048
Epoch 2/5
96/96 ━━━━━━━━━━━━━━━━━━━━ 714s 7s/step - accuracy: 0.9129 - loss: 0.2174 - val_accuracy: 0.9544 - val_loss: 0.1364
Epoch 3/5
96/96 ━━━━━━━━━━━━━━━━━━━━ 1042s 11s/step - accuracy: 0.9431 - loss: 0.1375 - val_accuracy: 0.9205 - val_loss: 0.1953
Epoch 4/5
96/96 ━━━━━━━━━━━━━━━━━━━━ 1427s 15s/step - accuracy: 0.9474 - loss: 0.1343 - val_accuracy: 0.9153 - val_loss: 0.2031
Epoch 5/5
96/96 ━━━━━━━━━━━━━━━━━━━━ 1185s 12s/step - accuracy: 0.9488 - loss: 0.1305 - val_accuracy: 0.9661 - val_loss: 0.0934


In [27]:
test_pred = model.predict(x_test)

24/24 ━━━━━━━━━━━━━━━━━━━━ 57s 2s/step


In [28]:
test_pred
# 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1

array([[8.29174995e-01],
       [8.84337071e-03],
       [9.99532521e-01],
       [9.15855765e-01],
       [9.99861777e-01],
       [2.94074975e-02],
       [5.26578166e-02],
       [1.00104660e-02],
       [9.87491846e-01],
       [9.91330504e-01],
       [8.37625265e-02],
       [2.52937041e-02],
       [9.90200520e-01],
       [6.96792603e-01],
       [9.99744594e-01],
       [9.96193945e-01],
       [1.12002958e-02],
       [9.98228550e-01],
       [9.97789025e-01],
       [9.99715388e-01],
       [4.17901278e-02],
       [8.87102067e-01],
       [1.27594359e-03],
       [6.80407230e-03],
       [1.54451087e-01],
       [9.28712904e-01],
       [4.40198958e-01],
       [9.37032640e-01],
       [9.43712592e-02],
       [1.20052872e-02],
       [8.56992602e-03],
       [1.04198291e-03],
       [9.80049014e-01],
       [9.99905109e-01],
       [9.60111201e-01],
       [1.14750769e-02],
       [9.53601778e-01],
       [2.96670407e-01],
       [2.35639978e-02],
       [9.99624372e-01],


In [29]:
y_test
# 1


array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,

In [30]:

def detect_face_mask(img):
    probabilities = model.predict(img.reshape(1,224,224,3)) 
    if probabilities > 0.5:
        return 0  
    else:
        return 1  

In [36]:
cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')


while True:
    ret, frame = cap.read()
    
    faces = face_cascade.detectMultiScale( frame ,minSize=(30, 30))


    
    for (x, y, w, h) in faces:
        
        face_image = frame[y:y+h, x:x+w]
        face_image = cv2.resize(face_image, (224, 224))
        
        prediction = detect_face_mask(face_image);
        font = cv2.FONT_HERSHEY_SIMPLEX
        if(prediction == 1):
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0))
            cv2.putText(frame, "mask detected", (x, y-10),font,0.7, (0, 255, 0))
        else:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255))
            cv2.putText(frame, "mask not detected", (x, y-10),font,0.7, (0,0,255))
    
    
    cv2.imshow('Window', frame)

    if cv2.waitKey(1) & 0xFF == ord('x'):
        break

cap.release()
cv2.destroyAllWindows()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 

In [31]:
train_pred = model.predict(x_train)

96/96 ━━━━━━━━━━━━━━━━━━━━ 301s 3s/step


In [32]:
train_pred

array([[0.9978147 ],
       [0.9990659 ],
       [0.00237012],
       ...,
       [0.00328567],
       [0.14403886],
       [0.02967915]], dtype=float32)

In [33]:
test_pred = np.where(test_pred > 0.5, 1, 0)
train_pred = np.where(train_pred > 0.5, 1, 0)


In [34]:
from sklearn.metrics import accuracy_score

test_accuracy = accuracy_score(y_test, test_pred)
train_accuracy = accuracy_score(y_train,train_pred)
print("test accuracy: ",test_accuracy)
print("train_accuracy: ",train_accuracy)

test accuracy:  0.9661016949152542
train_accuracy:  0.9729288975864319
